//
//  UIColor+STRAdditions.h
//
//  Generated by Zeplin on 11/9/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (STRAdditions)

+ (UIColor *)str_purplyColor;
+ (UIColor *)str_paleGreyColor;
+ (UIColor *)str_black88Color;
+ (UIColor *)str_paleGreyBackgroundColor;

@end
