//
//  UIColor+STRAdditions.m
//
//  Generated by Zeplin on 11/9/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+STRAdditions.h"

@implementation UIColor (STRAdditions)

+ (UIColor *)str_purplyColor {
	return [UIColor colorWithRed:155.0f / 255.0f green:47.0f / 255.0f blue:174.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)str_paleGreyColor {
	return [UIColor colorWithRed:220.0f / 255.0f green:220.0f / 255.0f blue:227.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)str_black88Color {
	return [UIColor colorWithWhite:0.0 alpha:0.88f];
}

+ (UIColor *)str_paleGreyBackgroundColor {
	return [UIColor colorWithRed:251.0f / 255.0f green:249.0f / 255.0f blue:252.0f / 255.0f alpha:1.0f];
}

@end
