//
//  UIFont+STRAdditions.h
//
//  Generated by Zeplin on 11/9/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIFont (STRAdditions)

+ (UIFont *)str_textStyle3Font;
+ (UIFont *)str_textStyleFont;
+ (UIFont *)str_textStyle5Font;
+ (UIFont *)str_textStyle4Font;
+ (UIFont *)str_textStyle2Font;

@end
