//
//  UIFont+STRAdditions.m
//
//  Generated by Zeplin on 11/9/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIFont+STRAdditions.h"

@implementation UIFont (STRAdditions)

+ (UIFont *)str_textStyle3Font {
	return [UIFont fontWithName:@"SFUIText-Medium" size:30.0f];
}

+ (UIFont *)str_textStyleFont {
	return [UIFont fontWithName:@"SFUIText-Medium" size:20.0f];
}

+ (UIFont *)str_textStyle5Font {
	return [UIFont fontWithName:@"SFUIText-Regular" size:20.0f];
}

+ (UIFont *)str_textStyle4Font {
	return [UIFont fontWithName:@"SFUIText-Regular" size:16.0f];
}

+ (UIFont *)str_textStyle2Font {
	return [UIFont fontWithName:@"SFUIText-Regular" size:13.0f];
}

@end
